//! FLUX.1-Kontext: instruction editing, against the real checkpoint.
//!
//! ```bash
//! SD_TEST_KONTEXT_GGUF=tests/golden/kontext/flux1-kontext-dev-Q4_K_S.gguf \
//! SD_TEST_T5_GGUF=... SD_TEST_FLUX_DIR=... \
//!   cargo test -p stable-diffusion-rs --features mlx --test mlx_kontext -- --nocapture
//! ```
//!
//! # Measuring an edit
//!
//! **Luminance, not RGB.** The obvious check — correlate the output against
//! the source in RGB — measures the wrong thing, because an instruction like
//! "make it winter" is *supposed* to change the colours. Measured on the same
//! pair: 0.498 in RGB against 0.817 in luminance, and the RGB figure moves
//! with how drastic the recolouring was rather than with how well the
//! structure survived.
//!
//! **And a control is required**, because a correlation is meaningless
//! without one: the same model, same prompt, same seed, no reference. That is
//! 0.127. The separation is the claim.
//!
//! Edge correlation was tried and rejected: snow removes almost all
//! high-frequency detail, so the edited image has a neighbour step of 2.6
//! against the source's 11, and edge agreement goes *negative* on a correct
//! edit.
#![cfg(feature = "mlx")]

use std::path::PathBuf;

use sd_models::mlx::flux::FluxConfig;
use stable_diffusion_rs::mlx::{FluxPaths, FluxPipeline, FluxRunConfig};
use stable_diffusion_rs::tensor::mlx::Array;

fn env_path(key: &str) -> Option<PathBuf> {
    std::env::var(key)
        .ok()
        .map(PathBuf::from)
        .filter(|p| p.exists())
}

fn luminance(w: usize, h: usize, rgb: &[u8]) -> Vec<f64> {
    (0..w * h)
        .map(|i| {
            let (r, g, b) = (
                rgb[i * 3] as f64,
                rgb[i * 3 + 1] as f64,
                rgb[i * 3 + 2] as f64,
            );
            0.299 * r + 0.587 * g + 0.114 * b
        })
        .collect()
}

fn correlate(a: &[f64], b: &[f64]) -> f64 {
    let n = a.len() as f64;
    let (ma, mb) = (a.iter().sum::<f64>() / n, b.iter().sum::<f64>() / n);
    let (mut num, mut da, mut db) = (0.0, 0.0, 0.0);
    for (x, y) in a.iter().zip(b) {
        num += (x - ma) * (y - mb);
        da += (x - ma).powi(2);
        db += (y - mb).powi(2);
    }
    num / (da.sqrt() * db.sqrt()).max(f64::EPSILON)
}

/// **The reference is preserved, and the instruction is applied.**
///
/// Measured against `QuantStack/FLUX.1-Kontext-dev-GGUF` at Q4_K_S: luminance
/// correlation 0.817 with the source, against 0.127 for the same run with no
/// reference. Snow applied, crab unchanged.
#[test]
fn kontext_edits_the_reference_rather_than_replacing_it() {
    let (Some(kontext), Some(t5), Some(dir)) = (
        env_path("SD_TEST_KONTEXT_GGUF"),
        env_path("SD_TEST_T5_GGUF"),
        env_path("SD_TEST_FLUX_DIR"),
    ) else {
        sd_tensor::skip_missing_fixture!(
            "SKIP: set SD_TEST_KONTEXT_GGUF, SD_TEST_T5_GGUF and SD_TEST_FLUX_DIR."
        );
        return;
    };

    let paths = FluxPaths::in_dir(&dir);
    // Kontext is dev-class: it carries a guidance embedding.
    let pipe = FluxPipeline::from_gguf(
        &kontext,
        &t5,
        &paths.clip,
        &paths.vae,
        &paths.clip_tokenizer,
        &paths.t5_tokenizer,
        FluxConfig::dev(),
        4,
        Default::default(),
    )
    .expect("loading Kontext");

    // A source with real structure, generated by the same model so that it
    // sits on the VAE's manifold — the trap `mlx_img2img` and the
    // InstructPix2Pix test both record.
    let source = FluxRunConfig {
        prompt: "a rusty crab on a beach at sunset".into(),
        width: 512,
        height: 512,
        steps: 8,
        guidance: 2.5,
        seed: 42,
    };
    let (w, h, src) = pipe.txt2img(&source).expect("source");

    let px: Vec<f32> = src.iter().map(|&b| b as f32 / 127.5 - 1.0).collect();
    let reference = Array::from_slice_f32(&px, &[1, h, w, 3]).unwrap();

    let edit = FluxRunConfig {
        prompt: "make it winter, with snow on the sand".into(),
        steps: 12,
        ..source.clone()
    };
    let (ew, eh, edited) = pipe.kontext(&edit, &reference).expect("kontext");
    assert_eq!((ew, eh), (w, h), "the reference's tokens came back off");

    // The control: the same instruction with no reference at all. Without this
    // the correlation below is a number with nothing to compare against.
    let (_, _, control) = pipe.txt2img(&edit).expect("control");

    let (l_src, l_edit, l_control) = (
        luminance(w, h, &src),
        luminance(w, h, &edited),
        luminance(w, h, &control),
    );
    let kept = correlate(&l_src, &l_edit);
    let baseline = correlate(&l_src, &l_control);
    eprintln!("kontext: luminance correlation {kept:.3}, control {baseline:.3}");

    assert!(
        kept > 0.6,
        "correlation {kept:.3} with the source: the reference was not preserved"
    );
    // **A margin, not a ratio.** The control can be *negative* — measured at
    // -0.642 on one run, because a snowy scene generated from scratch is the
    // photographic negative of a sunset one — and `kept > baseline * 2.0` is
    // satisfied by anything at all once the baseline goes below zero. A fixed
    // gap says what was meant.
    assert!(
        kept - baseline > 0.4,
        "correlation {kept:.3} is only {:.3} above the no-reference control \
         {baseline:.3}; the reference may not be reaching the model",
        kept - baseline
    );
    // And it is still a picture rather than a smooth field.
    let mean = edited.iter().map(|&b| b as f64).sum::<f64>() / edited.len() as f64;
    assert!((5.0..252.0).contains(&mean), "edited mean {mean:.1}");
}
