//! Golden verification for the samplers.
//!
//! The reference is generated by writing the same formulas out in numpy rather
//! than by importing k-diffusion, so agreement means the equations match — not
//! that two libraries happen to agree for reasons neither side states.

use std::collections::HashMap;
use std::path::PathBuf;

use sd_sample::{euler_ancestral_step, sigmas_for_steps, DpmSolverPlusPlus2M, Schedule};
use sd_tensor::{testing, DType, Device, Tensor};

/// The fixed sigma ladder the reference steps through.
const SIGMAS: [f64; 7] = [14.6146, 10.0, 6.0, 3.0, 1.5, 0.5, 0.0];

fn refs() -> Option<HashMap<String, Tensor>> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/golden/samplers/reference.safetensors");
    if !path.exists() {
        eprintln!(
            "SKIP: no reference data.\n\
             Generate it with:\n\
             \n    python3 xtask/golden/dump_reference.py samplers --output tests/golden\n"
        );
        return None;
    }
    Some(sd_tensor::safetensors::load(&path, &Device::Cpu).expect("loading reference"))
}

// -- structural: no reference data needed ---------------------------------

#[test]
fn sigmas_for_steps_returns_n_plus_one_descending() {
    let schedule = Schedule::sd15();
    for n in [1usize, 5, 20, 50] {
        let sigmas = sigmas_for_steps(&schedule, n);
        assert_eq!(sigmas.len(), n + 1, "n={n} needs n+1 boundaries");
        // Sampling starts at maximum noise. An ascending list runs happily and
        // returns noise, so the ordering is worth asserting directly.
        for pair in sigmas.windows(2) {
            assert!(
                pair[0] >= pair[1],
                "sigmas must descend, got {pair:?} for n={n}"
            );
        }
    }
}

#[test]
fn sigmas_for_steps_ends_at_zero() {
    let schedule = Schedule::sd15();
    let sigmas = sigmas_for_steps(&schedule, 20);
    assert_eq!(
        *sigmas.last().unwrap(),
        0.0,
        "the trailing 0.0 is a real entry"
    );
    assert!(sigmas[0] > 1.0, "the first sigma should be the noisiest");
}

#[test]
fn euler_with_zero_sigma_next_adds_no_noise() {
    // The final step lands on the clean image; adding noise back would undo
    // the last denoise and is invisible in any shape check.
    let dev = Device::Cpu;
    let x = Tensor::zeros((1, 4, 4, 4), DType::F32, &dev).unwrap();
    let denoised = Tensor::zeros((1, 4, 4, 4), DType::F32, &dev).unwrap();
    let noise = (Tensor::ones((1, 4, 4, 4), DType::F32, &dev).unwrap() * 1000.0).unwrap();

    let out = euler_ancestral_step(&x, &denoised, 0.5, 0.0, &noise).expect("step");
    let max = out
        .abs()
        .unwrap()
        .flatten_all()
        .unwrap()
        .max(0)
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    assert!(max < 1e-6, "noise leaked into the final step: max={max}");
}

#[test]
fn euler_sigma_up_clamp_prevents_a_nan_on_a_non_descending_pair() {
    // What the `min` in `sigma_up` is actually for.
    //
    // On a descending schedule it never binds: the raw value is
    // `s_next * sqrt(1 - (s_next/s)^2)`, and that factor is at most 1 whenever
    // `s_next <= s`. So no correctly-ordered golden data can detect its
    // removal — verified by deleting it and watching every numerical test
    // still pass.
    //
    // It earns its place on an out-of-order pair, where `s^2 - s_next^2` goes
    // negative and the raw expression is NaN. `f64::min` returns the non-NaN
    // operand, so the clamp turns that into a finite step instead of poisoning
    // the whole latent. Without it this test produces NaN.
    let dev = Device::Cpu;
    let x = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();
    let denoised = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();
    let noise = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();

    let out = euler_ancestral_step(&x, &denoised, 1.0, 2.0, &noise).expect("step");
    let values = out.flatten_all().unwrap().to_vec1::<f32>().unwrap();
    assert!(
        values.iter().all(|v| v.is_finite()),
        "sigma_next > sigma must not produce NaN; the min clamp is what prevents it"
    );
}

#[test]
fn dpmpp_first_step_falls_back_to_first_order() {
    // With no previous denoised there is nothing to extrapolate from, so the
    // first step must equal the first-order formula. A solver that reads
    // uninitialised state would differ here.
    let dev = Device::Cpu;
    let x = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();
    let denoised = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();

    let (sigma, sigma_next) = (10.0, 6.0);
    let mut solver = DpmSolverPlusPlus2M::new();
    let got = solver.step(&x, &denoised, sigma, sigma_next).expect("step");

    let h = (-sigma_next.ln()) - (-sigma.ln());
    let want =
        ((&x * (sigma_next / sigma)).unwrap() - (&denoised * ((-h).exp() - 1.0)).unwrap()).unwrap();
    testing::assert_close(&got, &want, 1e-6, "dpmpp first step").unwrap();
}

#[test]
fn dpmpp_reset_clears_state() {
    // Reusing a solver across images without reset silently corrupts the
    // second one — the state is carried, the shapes still line up, and the
    // output reads as a bad seed. Nothing else catches this.
    //
    // Modelled as two runs of the same two-step sequence, which is the shape
    // the hazard actually takes. Note the two steps use *different* denoised
    // tensors: with the same one on both, the second-order correction reduces
    // back to the first-order result and the bug hides.
    let dev = Device::Cpu;
    let x = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();
    let d1 = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();
    let d2 = Tensor::randn(0f32, 1f32, (1, 4, 4, 4), &dev).unwrap();

    let mut solver = DpmSolverPlusPlus2M::new();
    let first_a = solver.step(&x, &d1, 10.0, 6.0).expect("step");
    let first_b = solver.step(&first_a, &d2, 6.0, 3.0).expect("step");

    // Second "image" on the same solver: step one now sees leftover state.
    let dirty_a = solver.step(&x, &d1, 10.0, 6.0).expect("step");
    assert!(
        testing::closeness(&first_a, &dirty_a).unwrap().max_abs > 1e-6,
        "carried state should have changed the first step of the second run — \
         if it did not, this test cannot detect a missing reset"
    );

    // After reset the sequence must reproduce the first run exactly.
    solver.reset();
    let clean_a = solver.step(&x, &d1, 10.0, 6.0).expect("step");
    let clean_b = solver.step(&clean_a, &d2, 6.0, 3.0).expect("step");
    testing::assert_close(&first_a, &clean_a, 1e-6, "reset: step 1").unwrap();
    testing::assert_close(&first_b, &clean_b, 1e-6, "reset: step 2").unwrap();
}

// -- numerical -------------------------------------------------------------

#[test]
fn sigmas_match_reference() {
    let Some(refs) = refs() else { return };
    let want: Vec<f64> = refs
        .get("sigmas_20")
        .expect("sigmas_20")
        .to_vec1::<f64>()
        .expect("f64 sigmas");

    let got = sigmas_for_steps(&Schedule::sd15(), 20);
    assert_eq!(got.len(), want.len());
    for (i, (g, w)) in got.iter().zip(&want).enumerate() {
        assert!(
            (g - w).abs() < 1e-4,
            "sigma {i} diverged: got {g}, want {w}"
        );
    }
    eprintln!("sigmas_20: {} values, first {:.4}", got.len(), got[0]);
}

#[test]
fn euler_steps_match_reference() {
    let Some(refs) = refs() else { return };
    let x = refs.get("x").expect("x");
    let denoised = refs.get("denoised").expect("denoised");
    let noise = refs.get("noise").expect("noise");

    // Each step is independent: the reference applies every sigma pair to the
    // same starting x, so a divergence names one pair rather than accumulating.
    for i in 0..SIGMAS.len() - 1 {
        let got =
            euler_ancestral_step(x, denoised, SIGMAS[i], SIGMAS[i + 1], noise).expect("euler step");
        let want = refs
            .get(&format!("euler_step_{i}"))
            .unwrap_or_else(|| panic!("reference has no euler_step_{i}"));
        let c = testing::closeness(&got, want).expect("comparing");
        eprintln!(
            "euler_step_{i} (sigma {} -> {}): {c}",
            SIGMAS[i],
            SIGMAS[i + 1]
        );
        testing::assert_close(
            &got,
            want,
            testing::DEFAULT_ATOL,
            &format!("euler step {i}"),
        )
        .unwrap();
    }
}

#[test]
fn dpmpp_steps_match_reference() {
    let Some(refs) = refs() else { return };
    let denoised = refs.get("denoised").expect("denoised");

    // Sequential, with state carried — that is the whole point of this solver
    // and the thing most likely to be wrong.
    let mut solver = DpmSolverPlusPlus2M::new();
    let mut x = refs.get("x").expect("x").clone();
    for i in 0..SIGMAS.len() - 1 {
        x = solver
            .step(&x, denoised, SIGMAS[i], SIGMAS[i + 1])
            .expect("dpmpp step");
        let want = refs
            .get(&format!("dpmpp_step_{i}"))
            .unwrap_or_else(|| panic!("reference has no dpmpp_step_{i}"));
        let c = testing::closeness(&x, want).expect("comparing");
        eprintln!(
            "dpmpp_step_{i} (sigma {} -> {}): {c}",
            SIGMAS[i],
            SIGMAS[i + 1]
        );
        testing::assert_close(&x, want, testing::DEFAULT_ATOL, &format!("dpmpp step {i}")).unwrap();
    }
}
